name: CI

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@7
        with:
          node-version: v24.13.0

      - name: install dependencies
        run: npm ci

      - name: Test Lint
        run: npm run lint

      - name: Build project
        run: npm run build